name: Scheduled Python Script

on:
  schedule:
    - cron: '0 0 */7 * *'  # Runs every 7 days
  workflow_dispatch:        # ✅ Allow manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Required for GitHub Actions to push updates

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Needed for reset/rebase to work

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Force sync with remote main
        run: |
          git fetch origin main
          git reset --hard origin/main  # ✅ Ensures we are on the latest remote state

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade openpyxl pandas requests msal
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify OpenPyXL Installation
        run: python -c "import openpyxl; print('Openpyxl version:', openpyxl.__version__)"

      - name: Run Python scripts
        run: |
          python CoinGeckoTop5000.py
          python MultiExchangeTop500.py

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.Top500_CG }}
        run: |
          git add .
          git commit -m "Automated update - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/Fedric-Reform/Top500CG.git HEAD:main --force
