name: Scheduled Python Script

on:
  schedule:
    - cron: #'0 */24 * * *'  # Runs every 24 hours
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

permissions:
  contents: write  # Required for GitHub Actions to push updates

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade openpyxl pandas requests msal
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify OpenPyXL Installation
        run: python -c "import openpyxl; print('Openpyxl version:', openpyxl.__version__)"

      - name: Run Python scripts
        run: |
          # python GetTop500CG.py
          # python BinanceData.py
          # python BitgetData.py
          # python BybitData.py
          # python GateioData.py
          # python KuCoinData.py
          # python MEXCData.py
          # python OkxData.py

      - name: Setup Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Push Changes
        env:
          GH_PAT: ${{ secrets.Top500_CG }}
        run: |
          git add .
          git commit -m "Automated update - $(date)" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://x-access-token:${GH_PAT}@github.com/Fedric-Reform/Top500CG.git main
